//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_product
    {
        public long id { get; set; }
        public long product_id { get; set; }
        public long transaction_id { get; set; }
    
        public virtual product product { get; set; }
        public virtual transaction transaction { get; set; }
    }
}
